name 'version_databag'
maintainer 'Cerner Innovation, Inc'
maintainer_email 'Mike.Rzepka@cerner.com'
license 'Apache-2.0'
description 'Dynamically retrieve artifact versions from a data bag'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
issues_url 'https://github.com/cerner/version_databag/issues'
source_url 'https://github.com/cerner/version_databag'
chef_version '>= 12.0'
supports 'centos'
supports 'ubuntu'
version '1.1.0'
